import { APIGatewayEventIdentity, APIGatewayProxyEvent } from "aws-lambda";

/**
 * Generated by `sam local generate-event apigateway aws-proxy`
 * and extended to match {@link APIGatewayProxyEvent}.
 */
export const apiGatewayProxyEventStub: APIGatewayProxyEvent = {
  body: "",
  isBase64Encoded: false,
  resource: "/request",
  path: "/request",
  httpMethod: "GET",
  headers: {
    "X-AMZ-Date": "20170718T062915Z",
    Accept: "*/*",
    HeaderAuth1: "headerValue1",
    "CloudFront-Viewer-Country": "US",
    "CloudFront-Forwarded-Proto": "https",
    "CloudFront-Is-Tablet-Viewer": "false",
    "CloudFront-Is-Mobile-Viewer": "false",
    "User-Agent": "...",
  },
  multiValueHeaders: {},
  multiValueQueryStringParameters: null,
  queryStringParameters: {
    QueryString1: "queryValue1",
  },
  pathParameters: {},
  stageVariables: {
    StageVar1: "stageValue1",
  },
  requestContext: {
    authorizer: undefined,
    path: "/request",
    accountId: "123456789012",
    resourceId: "05c7jb",
    stage: "test",
    requestId: "...",
    identity: {
      apiKey: "...",
      sourceIp: "...",
      clientCert: {
        clientCertPem: "CERT_CONTENT",
        subjectDN: "www.example.com",
        issuerDN: "Example issuer",
        serialNumber: "a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1",
        validity: {
          notBefore: "May 28 12:30:02 2019 GMT",
          notAfter: "Aug  5 09:36:04 2021 GMT",
        },
      },
    } as APIGatewayEventIdentity,
    resourcePath: "/request",
    protocol: "HTTP/1.1",
    requestTimeEpoch: 1095379200.0,
    httpMethod: "GET",
    apiId: "",
  },
};
